# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'Android Signing keys'

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleRelease'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: key-store.jks
#
#  - task: Bash@3
#    inputs:
#      targetType: 'inline' # Optional. Options: filePath, inline
#      #filePath: # Required when targetType == FilePath
#      #arguments: # Optional
#      script: |
#        ls $AGENT_TEMPDIRECTORY
#      #workingDirectory: # Optional
#      #failOnStderr: false # Optional
#      #noProfile: true # Optional
#      #noRc: true # Optional

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      jarsign: true
      jarsignerKeystoreFile: 'e1782f6e-71ca-4387-9189-4f1ab4abb6f4'
      jarsignerKeystorePassword: '$(KEYSTORE_PASSWORD)'
      jarsignerKeystoreAlias: '$(KEYSTORE_ALIAS)'
      jarsignerKeyPassword: '$(KEY_PASSWORD)'
      zipalign: true

  - task: CopyFiles@2
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
