# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: 'Android Signing keys'
  - group: 'Runtime data'
  - name: SERVER_URL
    value: '$(SERVER_DOMAIN)'
  - name: CLIENT_TOKEN2
    value: '$(CLIENT_TOKEN)'

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: key-store.jks

  - task: DownloadSecureFile@1
    inputs:
      secureFile: google-services.json

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.TempDirectory)'
      contents: 'google-services.json'
      targetFolder: '$(Build.SourcesDirectory)/app'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleRelease'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '**/*.apk'
      apksign: true
      apksignerKeystoreFile: 'key-store.jks'
      apksignerKeystorePassword: '$(KEYSTORE_PASSWORD)'
      apksignerKeystoreAlias: '$(KEYSTORE_ALIAS)'
      apksignerKeyPassword: '$(KEY_PASSWORD)'
      # When it was set to true the task threw this error:
      # zipalign: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
      zipalign: false

  - task: CopyFiles@2
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
